name: "Create PR"
on: push

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    
    - name: Automatically Create Pull Requests
      uses: BaharaJr/create-pr@0.0.1

      with:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        title: "An automatically created PR!"